# Extra autostart processes
# exec-once = uwsm-app -- my-service

# Force French keyboard layout after all configs are loaded (workaround for intermittent US fallback)
exec-once = hyprctl keyword input:kb_layout fr
exec-once = [workspace 1 silent] uwsm app -- thunderbird
exec-once = [workspace 2 silent] uwsm app -- firefox
exec-once = [workspace 3 silent] uwsm app -- beeper
exec-once = [workspace 4 silent] uwsm app -- alacritty
exec-once = [workspace 6 silent] uwsm app -- nautilus
exec-once = uwsm app -- bash "$HOME/rclone_mount.sh"
exec-once = uwsm app -- bash "$HOME/serverannah_mount.sh"
exec-once = uwsm app -- kdeconnectd
exec-once = uwsm app -- kdeconnect-indicator
