# Application bindings
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, RETURN, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, E, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER SHIFT, B, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, omarchy-launch-browser --private
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
bindd = SUPER SHIFT, RETURN, Activity, exec, omarchy-launch-tui btop
bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = SUPER SHIFT, G, Signal, exec, omarchy-launch-or-focus ^signal$ "uwsm-app -- signal-desktop"
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus ^obsidian$ "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER SHIFT, W, Typora, exec, uwsm-app -- typora --enable-wayland-ime
bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- 1password

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
bindd = SUPER SHIFT ALT, A, Grok, exec, omarchy-launch-webapp "https://grok.com"
bindd = SUPER SHIFT, C, Calculator, exec, gnome-calculator
bindd = SUPER SHIFT, H, Email, exec, omarchy-launch-webapp "https://app.hey.com"
bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-webapp "https://youtube.com/"
bindd = SUPER SHIFT ALT, G, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
bindd = SUPER SHIFT CTRL, G, Google Messages, exec, omarchy-launch-or-focus-webapp "Google Messages" "https://messages.google.com/web/conversations"
bindd = SUPER SHIFT, P, Google Photos, exec, omarchy-launch-or-focus-webapp "Google Photos" "https://photos.google.com/"
bindd = SUPER SHIFT, X, X, exec, omarchy-launch-webapp "https://x.com/"
bindd = SUPER SHIFT ALT, X, X Post, exec, omarchy-launch-webapp "https://x.com/compose/post"

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu

bind = SUPER SHIFT, ESCAPE, exec, systemctl suspend
bind = SUPER SHIFT, code:49, exec, espanso restart
bindd = SUPER SHIFT, S, Hyprmon, exec, omarchy-launch-tui hyprmon
bindd = SUPER SHIFT CTRL, S, Load Monitor Profile, exec, hyprmon -profile "monitor only"
bindd = SUPER SHIFT ALT, S, Laptop screen on, exec, hyprctl keyword monitor "eDP-1, preferred, auto, 1.25"

# Numpad workspace navigation
# Remove this whole block if it causes issues.
bind = SUPER, KP_End, workspace, 1
bind = SUPER, KP_Down, workspace, 2
bind = SUPER, KP_Next, workspace, 3
bind = SUPER, KP_Left, workspace, 4
bind = SUPER, KP_Begin, workspace, 5
bind = SUPER, KP_Right, workspace, 6
bind = SUPER, KP_Home, workspace, 7
bind = SUPER, KP_Up, workspace, 8
bind = SUPER, KP_Prior, workspace, 9
bind = SUPER, KP_Insert, workspace, 10

bind = SUPER SHIFT, KP_End, movetoworkspace, 1
bind = SUPER SHIFT, KP_Down, movetoworkspace, 2
bind = SUPER SHIFT, KP_Next, movetoworkspace, 3
bind = SUPER SHIFT, KP_Left, movetoworkspace, 4
bind = SUPER SHIFT, KP_Begin, movetoworkspace, 5
bind = SUPER SHIFT, KP_Right, movetoworkspace, 6
bind = SUPER SHIFT, KP_Home, movetoworkspace, 7
bind = SUPER SHIFT, KP_Up, movetoworkspace, 8
bind = SUPER SHIFT, KP_Prior, movetoworkspace, 9
bind = SUPER SHIFT, KP_Insert, movetoworkspace, 10
